Fix list units json parameter validation
After go-sdk was upgraded to v1.0.0 json validation fails like this:

Gemini-cli:
> what systemd services are running?
X list_systemd_units_by_state (systemd-mcp MCP Server) {"verbose":false,"states":["running"]}
X params/states must be equal to one of the allowed values

Mcphost:
Error: Tool execution error: failed to call mcp tool: invalid params: validating "arguments":
	validating root: validating /properties/states: enum: [running] does not equal any of:
	[active dead inactive loaded mounted not-found plugged running all]

Fix by changing the `states` parameter from an array to a string and rename the field to
`state` to reflect that. This is also consistent with the other list units description in
systemd-mcp.go. Use the default schema from the struct - we already check for valid states
in the tool call.